kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: elk-stack
  labels:
    app: elasticsearch-logging
spec:
  selector:
    app: elasticsearch-logging
  type: NodePort
  ports:
    - port: 9200
      nodePort: 32520
      name: rest
    - port: 9300
      name: inter-node